services:
  mikmaq-dictionary-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mikmaq-dictionary-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./dictionary.json:/app/dictionary.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
